#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

sudo: false

matrix:
    include:
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Dev
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Release
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Dev
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Release

# http://docs.travis-ci.com/user/apt/
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libgdal-dev
            - libproj-dev
            - libsparsehash-dev

install:
    - cd ..
    - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git

script:
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    # GCC ignores the pragmas in the code that disable the "return-type" warning selectively, so use this workaround
    - if [ "${CXX}" = 'g++' ]; then WORKAROUND="-DCMAKE_CXX_FLAGS=-Wno-return-type"; else WORKAROUND=""; fi
    - if [ "${CXX}" = 'g++' ]; then CXX=g++-4.8; CC=gcc-4.8; fi
    - cmake -LA -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${WORKAROUND} ..
    - make VERBOSE=1
    # build and test each subproject by itself
    - cd $TRAVIS_BUILD_DIR
    - ./cmake/build_subprojects.sh ${BUILD_TYPE} ${WORKAROUND}

